### ISSUE TITLE
Inconsistent Formatting

### ISSUE THREAD

**Issue by MitchellTFord** [AustinWongParker/JavaTraining#1]
On [line #1](https://github.com/AustinWongParker/JavaTraining/blob/09109936674ae1111ae6046bb5da128e3e4602ad/Beginner%20Java/src/HelloWorld.java#L1) the opening bracket is on the same line as the class declaration, but on [line #2](https://github.com/AustinWongParker/JavaTraining/blob/09109936674ae1111ae6046bb5da128e3e4602ad/Beginner%20Java/src/HelloWorld.java#L2) the method signature has its opening bracket on the next line.

**Comment by AustinWongParker** [comment]
Thank you Mitchell!!!!
